import { test, expect } from '@playwright/test';

test('Default Split/Join colors survive sharing and JSON and appear in Excel', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Change Colors', exact: true }).click();
  await page.locator('#split_color').fill('#102030');
  await page.locator('#join_color').fill('#ffccee');
  await expect(page.locator('td.split')).toHaveCSS('background-color', 'rgb(16, 32, 48)');
  await expect(page.locator('td.split')).toHaveCSS('color', 'rgb(255, 255, 255)');
  await page.locator('td.split input').fill('Custom colors');
  await page.getByRole('button', { name: 'Split 10.0.0.0/16', exact: true }).click();
  await expect(page.locator('td.join')).toHaveCSS('background-color', 'rgb(255, 204, 238)');
  const config = await page.evaluate(() => (window as any).exportConfig(false));
  expect(config.block_colors).toEqual({ split: '#102030', join: '#ffccee' });
  const url = await page.evaluate(() => (window as any).getConfigUrl());
  await page.goto(url);
  await expect(page.locator('td.split').first()).toHaveCSS('background-color', 'rgb(16, 32, 48)');
  await expect(page.locator('td.join')).toHaveCSS('background-color', 'rgb(255, 204, 238)');
  const sheet = await page.evaluate(() => (window as any).buildExcelSubnetSheet());
  expect(sheet.E2.s.fill.fgColor.rgb).toBe('102030');
  expect(sheet.E2.s.font.color.rgb).toBe('ffffff');
  expect(sheet.F2.s.fill.fgColor.rgb).toBe('FFCCEE');
  await page.getByRole('button', { name: 'Change Colors', exact: true }).click();
  await page.getByRole('button', { name: 'Reset block colors', exact: true }).click();
  await expect(page.locator('td.split').first()).toHaveCSS('background-color', 'rgb(242, 127, 100)');
  await page.getByRole('button', { name: 'Undo color', exact: true }).click();
  await expect(page.locator('td.split').first()).toHaveCSS('background-color', 'rgb(16, 32, 48)');
  await page.evaluate(config => (window as any).importConfig(config), config);
  await expect(page.locator('td.join input')).toHaveValue('Custom colors');
  await page.evaluate(() => (window as any).importConfig({ config_version: '2', base_network: '10.0.0.0/16', subnets: { '10.0.0.0/16': {} } }));
  await expect(page.locator('td.split')).toHaveCSS('background-color', 'rgb(242, 127, 100)');
});

test('Right-click colors individual data and hierarchy cells and preserves them through split/join', async ({ page }) => {
  await page.goto('/');
  await page.locator('.row_hosts').click({ button: 'right' });
  await page.getByRole('button', { name: 'Quick color 1', exact: true }).click();
  await expect(page.locator('.row_hosts')).toHaveCSS('background-color', 'rgb(255, 173, 173)');
  await expect(page.locator('.row_address')).not.toHaveCSS('background-color', 'rgb(255, 173, 173)');
  await page.locator('td.split input').click({ button: 'right' });
  await page.getByRole('button', { name: 'Quick color 7', exact: true }).click();
  await expect(page.locator('td.split')).toHaveCSS('background-color', 'rgb(189, 178, 255)');
  await expect(page.locator('#calcbody tr')).toHaveCount(1);
  await page.getByRole('button', { name: 'Split 10.0.0.0/16', exact: true }).click();
  await expect(page.locator('td.join')).toHaveCSS('background-color', 'rgb(189, 178, 255)');
  await expect(page.locator('.row_hosts').first()).toHaveCSS('background-color', 'rgb(255, 173, 173)');
  await page.locator('td.split input').first().click({ button: 'right' });
  await page.getByRole('button', { name: 'Quick color 4', exact: true }).click();
  await expect(page.locator('td.join')).toHaveCSS('background-color', 'rgb(189, 178, 255)');
  const url = await page.evaluate(() => (window as any).getConfigUrl());
  await page.goto(url);
  await expect(page.locator('td.split').first()).toHaveCSS('background-color', 'rgb(202, 255, 191)');
  const sheet = await page.evaluate(() => (window as any).buildExcelSubnetSheet());
  expect(sheet.D2.s.fill.fgColor.rgb).toBe('FFADAD');
  expect(sheet.E2.s.fill.fgColor.rgb).toBe('CAFFBF');
  expect(sheet.F2.s.fill.fgColor.rgb).toBe('BDB2FF');
  await page.getByRole('button', { name: 'Join 10.0.0.0/16', exact: true }).click();
  await expect(page.locator('td.split')).toHaveCSS('background-color', 'rgb(189, 178, 255)');
  await page.locator('td.split input').click({ button: 'right' });
  await page.getByRole('button', { name: 'Reset cell', exact: true }).click();
  await expect(page.locator('td.split')).toHaveCSS('background-color', 'rgb(242, 127, 100)');
});

test('Drag paints multiple individual cells in one undo operation and Escape stops painting', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Split 10.0.0.0/16', exact: true }).click();
  await page.getByRole('button', { name: 'Change Colors', exact: true }).click();
  await page.locator('#paint_scope').selectOption('cell');
  await page.getByRole('button', { name: 'Color 2', exact: true }).click();
  const cells = page.locator('.row_hosts');
  const first = (await cells.first().boundingBox())!;
  const last = (await cells.last().boundingBox())!;
  await page.mouse.move(first.x + 20, first.y + first.height / 2);
  await page.mouse.down();
  await page.mouse.move(last.x + 20, last.y + last.height / 2, { steps: 12 });
  await page.mouse.up();
  for (const cell of await cells.all()) await expect(cell).toHaveCSS('background-color', 'rgb(255, 214, 165)');
  await page.getByRole('button', { name: 'Undo color', exact: true }).click();
  for (const cell of await cells.all()) await expect(cell).not.toHaveCSS('background-color', 'rgb(255, 214, 165)');
  await expect(page.getByRole('button', { name: 'Undo color', exact: true })).toBeDisabled();
  await page.keyboard.press('Escape');
  await cells.first().click();
  await expect(cells.first()).not.toHaveCSS('background-color', 'rgb(255, 214, 165)');
  await expect(page.locator('#calcbody tr')).toHaveCount(2);
});

test('Quick palette fits a narrow viewport and custom color edits no notes or structure', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 700 });
  await page.goto('/');
  await page.locator('td.split input').fill('Keep this note');
  await page.locator('td.split input').click({ button: 'right' });
  const panel = page.getByRole('dialog', { name: 'Quick cell colors' });
  const box = (await panel.boundingBox())!;
  expect(box.x).toBeGreaterThanOrEqual(0);
  expect(box.x + box.width).toBeLessThanOrEqual(375);
  expect(box.y + box.height).toBeLessThanOrEqual(700);
  await page.locator('#quick_custom_color').fill('#123456');
  await expect(page.locator('td.split')).toHaveCSS('background-color', 'rgb(18, 52, 86)');
  await expect(page.locator('td.split input')).toHaveValue('Keep this note');
  await expect(page.locator('#calcbody tr')).toHaveCount(1);
});
